const stateCity = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Rajahmundry",
    "Tirupati",
    "Kadapa",
    "Anantapur",
    "Eluru",
    "Ongole",
    "Kakinada",
    "Chittoor",
    "Srikakulam",
    "Nandyal",
    "Machilipatnam",
    "Tenali",
    "Proddatur",
    "Adoni",
    "Madanapalle",
  ],

  "Arunachal Pradesh": [
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Tawang",
    "Bomdila",
    "Ziro",
    "Roing",
    "Along",
    "Tezu",
    "Daporijo",
    "Khonsa",
    "Seppa",
    "Yingkiong",
    "Anini",
    "Changlang",
    "Dirang",
    "Namsai",
    "Koloriang",
    "Hayuliang",
    "Pangin",
  ],

  Assam: [
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Bongaigaon",
    "Karimganj",
    "Diphu",
    "Barpeta",
    "Goalpara",
    "Dhubri",
    "Sibsagar",
    "Lakhimpur",
    "Hailakandi",
    "North Lakhimpur",
    "Morigaon",
    "Nalbari",
    "Golaghat",
  ],

  Bihar: [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Purnia",
    "Darbhanga",
    "Arrah",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chhapra",
    "Bettiah",
    "Sasaram",
    "Hajipur",
    "Siwan",
    "Motihari",
    "Dehri",
    "Jehanabad",
    "Samastipur",
    "Buxar",
  ],

  Chhattisgarh: [
    "Raipur",
    "Bhilai",
    "Bilaspur",
    "Korba",
    "Durg",
    "Rajnandgaon",
    "Jagdalpur",
    "Ambikapur",
    "Raigarh",
    "Dhamtari",
    "Kanker",
    "Mahasamund",
    "Chirmiri",
    "Dalli-Rajhara",
    "Janjgir",
    "Baikunthpur",
    "Bhatapara",
    "Kawardha",
    "Tilda",
    "Dongargarh",
  ],

  Goa: [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Curchorem",
    "Sanquelim",
    "Bicholim",
    "Valpoi",
    "Canacona",
    "Quepem",
    "Mormugao",
    "Assagao",
    "Sanguem",
    "Dabolim",
    "Aldona",
    "Calangute",
    "Verna",
    "Chicalim",
    "Pernem",
  ],

  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Gandhinagar",
    "Junagadh",
    "Anand",
    "Nadiad",
    "Navsari",
    "Mehsana",
    "Bharuch",
    "Porbandar",
    "Godhra",
    "Valsad",
    "Amreli",
    "Palanpur",
    "Morbi",
    "Veraval",
  ],

  Haryana: [
    "Faridabad",
    "Gurgaon",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Hisar",
    "Karnal",
    "Sonipat",
    "Panchkula",
    "Bhiwani",
    "Rewari",
    "Sirsa",
    "Bahadurgarh",
    "Jind",
    "Kaithal",
    "Palwal",
    "Kurukshetra",
    "Jhajjar",
    "Fatehabad",
  ],

  "Himachal Pradesh": [
    "Shimla",
    "Mandi",
    "Solan",
    "Dharamshala",
    "Kullu",
    "Bilaspur",
    "Chamba",
    "Hamirpur",
    "Una",
    "Nahan",
    "Palampur",
    "Sundarnagar",
    "Paonta Sahib",
    "Nalagarh",
    "Jogindernagar",
    "Rampur",
    "Nurpur",
    "Kangra",
    "Keylong",
    "Rohru",
  ],

  Jharkhand: [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Chaibasa",
    "Phusro",
    "Adityapur",
    "Chirkunda",
    "Medininagar",
    "Jhumri Telaiya",
    "Gumia",
    "Latehar",
    "Sahibganj",
    "Simdega",
    "Ghatshila",
    "Pakur",
  ],

  Karnataka: [
    "Bangalore",
    "Mysore",
    "Hubli",
    "Mangalore",
    "Belgaum",
    "Davanagere",
    "Bellary",
    "Bijapur",
    "Shimoga",
    "Tumkur",
    "Raichur",
    "Hassan",
    "Bidar",
    "Udupi",
    "Hospet",
    "Chitradurga",
    "Gulbarga",
    "Mandya",
    "Kolar",
    "Chikmagalur",
  ],

  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Alappuzha",
    "Kannur",
    "Palakkad",
    "Kottayam",
    "Malappuram",
    "Pathanamthitta",
    "Idukki",
    "Ernakulam",
    "Wayanad",
    "Chengannur",
    "Kasaragod",
    "Varkala",
    "Thalassery",
    "Nedumangad",
    "Kunnamkulam",
  ],

  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Gwalior",
    "Jabalpur",
    "Ujjain",
    "Sagar",
    "Satna",
    "Rewa",
    "Ratlam",
    "Dewas",
    "Katni",
    "Chhindwara",
    "Shivpuri",
    "Vidisha",
    "Khandwa",
    "Itarsi",
    "Hoshangabad",
    "Sehore",
    "Betul",
    "Morena",
  ],

  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Thane",
    "Aurangabad",
    "Solapur",
    "Amravati",
    "Kolhapur",
    "Sangli",
    "Jalgaon",
    "Akola",
    "Latur",
    "Ahmednagar",
    "Chandrapur",
    "Nanded",
    "Wardha",
    "Parbhani",
    "Satara",
    "Beed",
  ],

  Manipur: [
    "Imphal",
    "Thoubal",
    "Kakching",
    "Bishnupur",
    "Churachandpur",
    "Ukhrul",
    "Senapati",
    "Tamenglong",
    "Jiribam",
    "Moirang",
    "Kangpokpi",
    "Moreh",
    "Noney",
    "Kangla",
    "Lamlai",
    "Saitu",
    "Lilong",
    "Wangjing",
    "Yairipok",
    "Khongjom",
  ],

  Meghalaya: [
    "Shillong",
    "Tura",
    "Nongstoin",
    "Jowai",
    "Baghmara",
    "Williamnagar",
    "Resubelpara",
    "Mairang",
    "Nongpoh",
    "Sohra",
    "Cherrapunjee",
    "Dawki",
    "Mawkyrwat",
    "Umling",
    "Khliehriat",
    "Amlarem",
    "Madanrting",
    "Pynthorumkhrah",
    "Umroi",
    "Nongmynsong",
  ],

  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Serchhip",
    "Kolasib",
    "Lawngtlai",
    "Saiha",
    "Biate",
    "Saitual",
    "Hnahthial",
    "North Vanlaiphai",
    "Tlabung",
    "Thenzawl",
    "Vairengte",
    "Zawlnuam",
    "Reiek",
    "Sialsuk",
    "Sairang",
    "East Lungdar",
    "Darlawn",
  ],

  Nagaland: [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    "Mon",
    "Phek",
    "Kiphire",
    "Longleng",
    "Peren",
    "Chumukedima",
    "Medziphema",
    "Jalukie",
    "Tseminyu",
    "Pfutsero",
    "Aboi",
    "Meluri",
    "Tuli",
    "Bhandari",
  ],

  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Berhampur",
    "Sambalpur",
    "Puri",
    "Balasore",
    "Baripada",
    "Bhadrak",
    "Angul",
    "Jharsuguda",
    "Dhenkanal",
    "Rayagada",
    "Paradeep",
    "Bargarh",
    "Kendujhar",
    "Koraput",
    "Jeypore",
    "Sundargarh",
    "Nayagarh",
  ],

  Punjab: [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Hoshiarpur",
    "Mohali",
    "Batala",
    "Pathankot",
    "Moga",
    "Abohar",
    "Khanna",
    "Phagwara",
    "Barnala",
    "Fazilka",
    "Rajpura",
    "Zirakpur",
    "Firozpur",
    "Kapurthala",
    "Malerkotla",
  ],

  Rajasthan: [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Udaipur",
    "Ajmer",
    "Alwar",
    "Bharatpur",
    "Sikar",
    "Pali",
    "Tonk",
    "Barmer",
    "Bhilwara",
    "Chittorgarh",
    "Jhunjhunu",
    "Nagaur",
    "Hanumangarh",
    "Dausa",
    "Sawai Madhopur",
    "Jaisalmer",
  ],

  Sikkim: [
    "Gangtok",
    "Namchi",
    "Mangan",
    "Gyalshing",
    "Rangpo",
    "Singtam",
    "Jorethang",
    "Pakyong",
    "Ravangla",
    "Melli",
    "Soreng",
    "Yangang",
    "Dentam",
    "Chungthang",
    "Naya Bazar",
    "Makha",
    "Rhenock",
    "Yuksom",
    "Lachung",
    "Zuluk",
  ],

  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Erode",
    "Tiruppur",
    "Vellore",
    "Thoothukudi",
    "Dindigul",
    "Thanjavur",
    "Nagercoil",
    "Kanchipuram",
    "Cuddalore",
    "Kumbakonam",
    "Karur",
    "Nagapattinam",
    "Pudukkottai",
    "Sivakasi",
  ],

  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Ramagundam",
    "Mahbubnagar",
    "Nalgonda",
    "Adilabad",
    "Siddipet",
    "Miryalaguda",
    "Suryapet",
    "Jagtial",
    "Mancherial",
    "Bodhan",
    "Zaheerabad",
    "Medak",
    "Kamareddy",
    "Vikarabad",
    "Bhadradri Kothagudem",
  ],

  Tripura: [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Kailasahar",
    "Ambassa",
    "Belonia",
    "Khowai",
    "Sabroom",
    "Sonamura",
    "Teliamura",
    "Panisagar",
    "Bishalgarh",
    "Ranirbazar",
    "Melaghar",
    "Kamalpur",
    "Amarpur",
    "Gandacherra",
    "Jirania",
    "Boxanagar",
    "Kanchanpur",
  ],

  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Ghaziabad",
    "Agra",
    "Varanasi",
    "Meerut",
    "Allahabad",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Noida",
    "Jhansi",
    "Firozabad",
    "Rampur",
    "Muzaffarnagar",
    "Faizabad",
    "Shahjahanpur",
    "Mathura",
  ],

  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Roorkee",
    "Haldwani",
    "Rudrapur",
    "Nainital",
    "Kashipur",
    "Pithoragarh",
    "Tehri",
    "Mussoorie",
    "Almora",
    "Champawat",
    "Ranikhet",
    "Bageshwar",
    "Devprayag",
    "Srinagar",
    "Kotdwar",
    "New Tehri",
    "Vikasnagar",
    "Doiwala",
  ],

  "West Bengal": [
    "Kolkata",
    "Asansol",
    "Siliguri",
    "Durgapur",
    "Howrah",
    "Bardhaman",
    "Malda",
    "Kharagpur",
    "Haldia",
    "Baharampur",
    "Jalpaiguri",
    "Ranaghat",
    "Darjeeling",
    "Balurghat",
    "Raiganj",
    "Krishnanagar",
    "Habra",
    "Midnapore",
    "Bankura",
    "Cooch Behar",
  ],

  "United States": [
    "New York",
    "Los Angeles",
    "San Francisco",
    "Chicago",
    "Las Vegas",
    "Orlando",
    "Washington D.C.",
    "Seattle",
    "Boston",
    "Miami",
  ],
  "United Kingdom": [
    "London",
    "Manchester",
    "Edinburgh",
    "Birmingham",
    "Glasgow",
  ],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah"],
  Thailand: ["Bangkok", "Phuket", "Chiang Mai", "Pattaya"],
  Singapore: ["Singapore"],
  France: ["Paris", "Nice", "Lyon", "Marseille"],
  Germany: ["Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  Nepal: ["Kathmandu", "Pokhara", "Lumbini", "Chitwan"],
  "Sri Lanka": ["Colombo", "Kandy", "Galle", "Negombo"],
  Canada: ["Toronto", "Vancouver", "Montreal", "Ottawa", "Calgary"],
  Japan: ["Tokyo", "Kyoto", "Osaka", "Hiroshima", "Nara"],
  Malaysia: ["Kuala Lumpur", "George Town", "Langkawi", "Malacca"],
  Indonesia: ["Bali", "Jakarta", "Yogyakarta"],
  China: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Hong Kong"],
};
